FROM node:18-bullseye

WORKDIR /app

COPY ./frontend ./
COPY ./frontend/package.json ./package.json
COPY ./frontend/package-lock.json ./package-lock.json 
WORKDIR /app/frontend


RUN npm install

RUN npm run build

EXPOSE 3001

CMD [ "npm", "start" ]