FROM node:18-bullseye
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
WORKDIR /app
COPY ./frontend/package.json ./package.json
COPY ./frontend/package-lock.json ./package-lock.json 

WORKDIR /app/frontend

COPY ./frontend ./

RUN npm install
RUN npm run build

EXPOSE 3001

CMD [ "npm", "start" ]
