name: Continuous Deployment (Prod) (Frontend)
on: 
    push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD}}
            - name: Build and push to Docker Hub    
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.frontend
                push: true
                tags: alexgoot/staff_frontend:${{ github.sha }}  
                build-args: |
                      NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}
                      NEXT_PUBLIC_WS_URL=${{ secrets.WS_URL }}
            - name: Deploy to VM
              run: |
                # Save the SSH private key from GitHub secrets to a file
                echo "${{ secrets.SSH_KEY }}" > ~/ssh_key
      
                # Set correct file permissions for the SSH key rwx - 110
                chmod 600 ~/ssh_key
      
                # SSH to the VM and stop/remove the old container, then run the new container
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key Shrirang@4.213.167.255 << 'EOF'
                  sudo docker stop frontend || true
                  sudo docker rm frontend || true
      
                 sudo docker run -d \
                    -p 3001:3001 \
                    -e USER_JWT_SECRET='${{ secrets.USER_JWT_SECRET }}' \
                    -e OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
                    -e API_URL='${{ secrets.API_URL }}' \
                    --name frontend \
                    alexgoot/staff_frontend:${{ github.sha }} << 'EOF'
